/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * harvest-api
 *  HarvestOS is a custom learning management platform for SERC

    It purposefully blends the learning management system with the
    game based learning platform to create a unique learning.

    
 * OpenAPI spec version: 0.3.5
 */
import {
  rest
} from 'msw'
import {
  faker
} from '@faker-js/faker'

export const getEchoMock = () => ({message: faker.random.word()})

export const getGetHealthMock = () => ({all_ok: faker.datatype.boolean(), db_ok: faker.datatype.boolean(), queue_ok: faker.datatype.boolean(), timestamp: `${faker.date.past().toISOString().split('.')[0]}Z`})

export const getExtMSW = () => [
rest.get('*/api/ext/echo', (_req, res, ctx) => {
        return res(
          ctx.delay(1000),
          ctx.status(200, 'Mocked status'),
ctx.json(getEchoMock()),
        )
      }),rest.get('*/api/ext/healthcheck', (_req, res, ctx) => {
        return res(
          ctx.delay(1000),
          ctx.status(200, 'Mocked status'),
ctx.json(getGetHealthMock()),
        )
      }),]
