/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * harvest-api
 *  HarvestOS is a custom learning management platform for SERC

    It purposefully blends the learning management system with the
    game based learning platform to create a unique learning.

    
 * OpenAPI spec version: 0.3.5
 */
import type { BodyLoginForAuthTokenGrantType } from './bodyLoginForAuthTokenGrantType';
import type { BodyLoginForAuthTokenClientId } from './bodyLoginForAuthTokenClientId';
import type { BodyLoginForAuthTokenClientSecret } from './bodyLoginForAuthTokenClientSecret';

export interface BodyLoginForAuthToken {
  grant_type?: BodyLoginForAuthTokenGrantType;
  username: string;
  password: string;
  scope?: string;
  client_id?: BodyLoginForAuthTokenClientId;
  client_secret?: BodyLoginForAuthTokenClientSecret;
}
