/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * harvest-api
 *  HarvestOS is a custom learning management platform for SERC

    It purposefully blends the learning management system with the
    game based learning platform to create a unique learning.

    
 * OpenAPI spec version: 0.3.5
 */

/**
 *  Class preferences are used to override player    
    
 */
export interface ClassGamePreferenceResponse {
  createdAt: string;
  updatedAt: string;
  id: string;
  isMusicMuted: boolean;
  isVoiceMuted: boolean;
  quality: string;
  isEnabled: boolean;
}
