/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * harvest-api
 *  HarvestOS is a custom learning management platform for SERC

    It purposefully blends the learning management system with the
    game based learning platform to create a unique learning.

    
 * OpenAPI spec version: 0.3.5
 */

/**
 *   A generic model that represent portion of the content
    of a teachable unit or weekly topic that can be updated.

    This is typically used to update a particular field e.g
    experience, represent, apply on it's own.

    The use case is around using debounce to update the content
    
 */
export interface ContentUpdateRequest {
  content: string;
}
