/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * harvest-api
 *  HarvestOS is a custom learning management platform for SERC

    It purposefully blends the learning management system with the
    game based learning platform to create a unique learning.

    
 * OpenAPI spec version: 0.3.5
 */

/**
 * 
    A weekly teachable topic that belongs to a teachable unit
    this model allows you to create a weekly topic in draft mode.

    The only thing the user know at this time is the title,
    the rest of the information will be added later.

    A number will be assigned to the weekly topic based on the
    number of weekly topics in the teachable unit.
    
 */
export interface DraftWeeklyTopicCreateRequest {
  title: string;
}
