/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * harvest-api
 *  HarvestOS is a custom learning management platform for SERC

    It purposefully blends the learning management system with the
    game based learning platform to create a unique learning.

    
 * OpenAPI spec version: 0.3.5
 */
import type { DraftTeachableUnitRequestLearningIntention } from './draftTeachableUnitRequestLearningIntention';
import type { DraftTeachableUnitRequestStemCirruculumOutcomes } from './draftTeachableUnitRequestStemCirruculumOutcomes';
import type { DraftTeachableUnitRequestCoreContent } from './draftTeachableUnitRequestCoreContent';
import type { DraftTeachableUnitRequestStemPractices } from './draftTeachableUnitRequestStemPractices';
import type { DraftTeachableUnitRequestLearningProgressions } from './draftTeachableUnitRequestLearningProgressions';
import type { DraftTeachableUnitRequestLearningSuccessCriteria } from './draftTeachableUnitRequestLearningSuccessCriteria';
import type { DraftTeachableUnitRequestResources } from './draftTeachableUnitRequestResources';

/**
 *  Body of the request to create a teachable unit
    
 */
export interface DraftTeachableUnitRequest {
  title: string;
  number: number;
  learningIntention: DraftTeachableUnitRequestLearningIntention;
  stemCirruculumOutcomes: DraftTeachableUnitRequestStemCirruculumOutcomes;
  coreContent: DraftTeachableUnitRequestCoreContent;
  stemPractices: DraftTeachableUnitRequestStemPractices;
  learningProgressions: DraftTeachableUnitRequestLearningProgressions;
  learningSuccessCriteria: DraftTeachableUnitRequestLearningSuccessCriteria;
  resources: DraftTeachableUnitRequestResources;
  schoolYearId: string;
  schoolTermId: string;
}
