/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * harvest-api
 *  HarvestOS is a custom learning management platform for SERC

    It purposefully blends the learning management system with the
    game based learning platform to create a unique learning.

    
 * OpenAPI spec version: 0.3.5
 */
import type { DraftWeeklyTopicAbridgedResponse } from './draftWeeklyTopicAbridgedResponse';
import type { DraftTeachableUnitResponseLearningIntention } from './draftTeachableUnitResponseLearningIntention';
import type { DraftTeachableUnitResponseStemCirruculumOutcomes } from './draftTeachableUnitResponseStemCirruculumOutcomes';
import type { DraftTeachableUnitResponseCoreContent } from './draftTeachableUnitResponseCoreContent';
import type { DraftTeachableUnitResponseStemPractices } from './draftTeachableUnitResponseStemPractices';
import type { DraftTeachableUnitResponseTeacherNotes } from './draftTeachableUnitResponseTeacherNotes';
import type { DraftTeachableUnitResponseLearningProgressions } from './draftTeachableUnitResponseLearningProgressions';
import type { DraftTeachableUnitResponseLearningSuccessCriteria } from './draftTeachableUnitResponseLearningSuccessCriteria';
import type { DraftTeachableUnitResponseResources } from './draftTeachableUnitResponseResources';

/**
 *  Used by the specific endpoint to get the full
    information of a teachable unit. This build on the
    abridged response
    
 */
export interface DraftTeachableUnitResponse {
  createdAt: string;
  updatedAt: string;
  id: string;
  number: number;
  title: string;
  schoolYearId: string;
  schoolTermId: string;
  draftWeeklyTopics: DraftWeeklyTopicAbridgedResponse[];
  learningIntention: DraftTeachableUnitResponseLearningIntention;
  stemCirruculumOutcomes: DraftTeachableUnitResponseStemCirruculumOutcomes;
  coreContent: DraftTeachableUnitResponseCoreContent;
  stemPractices: DraftTeachableUnitResponseStemPractices;
  teacherNotes: DraftTeachableUnitResponseTeacherNotes;
  learningProgressions: DraftTeachableUnitResponseLearningProgressions;
  learningSuccessCriteria: DraftTeachableUnitResponseLearningSuccessCriteria;
  resources: DraftTeachableUnitResponseResources;
}
