/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * harvest-api
 *  HarvestOS is a custom learning management platform for SERC

    It purposefully blends the learning management system with the
    game based learning platform to create a unique learning.

    
 * OpenAPI spec version: 0.3.5
 */
import type { DraftWeeklyTopicRequestExperience } from './draftWeeklyTopicRequestExperience';
import type { DraftWeeklyTopicRequestRepresent } from './draftWeeklyTopicRequestRepresent';
import type { DraftWeeklyTopicRequestApply } from './draftWeeklyTopicRequestApply';

/**
 *  A weekly teachable topic that belongs to a teachable unit
    this model allows you to create a weekly topic in draft mode

    Note: that the unit_id should be passed as a query parameter
    
 */
export interface DraftWeeklyTopicRequest {
  title: string;
  number: number;
  experience: DraftWeeklyTopicRequestExperience;
  represent: DraftWeeklyTopicRequestRepresent;
  apply: DraftWeeklyTopicRequestApply;
}
