/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * harvest-api
 *  HarvestOS is a custom learning management platform for SERC

    It purposefully blends the learning management system with the
    game based learning platform to create a unique learning.

    
 * OpenAPI spec version: 0.3.5
 */

/**
 *  Model to create a teachable unit in draft mode
    During the time of creating a model the only thing
    the user is able to provide is the title,
    the rest of the information will be added later.

    The handler endpoint will assign a number based on
    the number of teachable units in the term.
    
 */
export interface DraftTeachableUnitCreateRequest {
  title: string;
}
