/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * harvest-api
 *  HarvestOS is a custom learning management platform for SERC

    It purposefully blends the learning management system with the
    game based learning platform to create a unique learning.

    
 * OpenAPI spec version: 0.3.5
 */

/**
 *  Abridged version of the weekly topic, primarily
    used in conjunction with the abridged teachable unit
    for the user interface to build navigation
    
 */
export interface DraftWeeklyTopicAbridgedResponse {
  createdAt: string;
  updatedAt: string;
  id: string;
  number: number;
  title: string;
  schoolYearId: string;
  schoolTermId: string;
  draftTeachableUnitId: string;
}
