/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * harvest-api
 *  HarvestOS is a custom learning management platform for SERC

    It purposefully blends the learning management system with the
    game based learning platform to create a unique learning.

    
 * OpenAPI spec version: 0.3.5
 */
import type { DraftWeeklyTopicAbridgedResponse } from './draftWeeklyTopicAbridgedResponse';

/**
 *  A teachable unit in draft mode with it's
    basic information to show the navigation, once the
    user selects the teachable unit, the full information
    will loaded by the specific endpoint
    
 */
export interface DraftTeachableUnitAbridgedResponse {
  createdAt: string;
  updatedAt: string;
  id: string;
  number: number;
  title: string;
  schoolYearId: string;
  schoolTermId: string;
  draftWeeklyTopics: DraftWeeklyTopicAbridgedResponse[];
}
