/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * harvest-api
 *  HarvestOS is a custom learning management platform for SERC

    It purposefully blends the learning management system with the
    game based learning platform to create a unique learning.

    
 * OpenAPI spec version: 0.3.5
 */

/**
 *  Provides a health check response with a timestamp

    All cloud native applications should provide a health check endpoint
    for loadbalancers to see if the application is healthy
    
 */
export interface HealthCheckResponse {
  all_ok: boolean;
  db_ok: boolean;
  queue_ok: boolean;
  timestamp: string;
}
