/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * harvest-api
 *  HarvestOS is a custom learning management platform for SERC

    It purposefully blends the learning management system with the
    game based learning platform to create a unique learning.

    
 * OpenAPI spec version: 0.3.5
 */

/**
 * 
    A user is asking to reset their password

    This will result in a token being sent out to them which they can use
    with the following model to reset their password
    
 */
export interface InitiateResetPasswordRequest {
  email: string;
}
