/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * harvest-api
 *  HarvestOS is a custom learning management platform for SERC

    It purposefully blends the learning management system with the
    game based learning platform to create a unique learning.

    
 * OpenAPI spec version: 0.3.5
 */

/**
 *  A simple request to sign up a user with an email and password    
    
 */
export interface SignupRequest {
  password: string;
  email: string;
  firstName: string;
  lastName: string;
}
