/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * harvest-api
 *  HarvestOS is a custom learning management platform for SERC

    It purposefully blends the learning management system with the
    game based learning platform to create a unique learning.

    
 * OpenAPI spec version: 0.3.5
 */
import type { TeacherAssignmentResponseEndDate } from './teacherAssignmentResponseEndDate';

export interface TeacherAssignmentResponse {
  createdAt: string;
  updatedAt: string;
  id: string;
  active: boolean;
  startDate: string;
  endDate: TeacherAssignmentResponseEndDate;
  teacherId: string;
  userId: string;
  schoolId: string;
  schoolClassId: string;
  schoolName: string;
  schoolClassName: string;
  logoUrl: string;
}
