/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * harvest-api
 *  HarvestOS is a custom learning management platform for SERC

    It purposefully blends the learning management system with the
    game based learning platform to create a unique learning.

    
 * OpenAPI spec version: 0.3.5
 */
import type { TeachableUnitDetailResponseLearningIntention } from './teachableUnitDetailResponseLearningIntention';
import type { TeachableUnitDetailResponseStemCurriculumOutlines } from './teachableUnitDetailResponseStemCurriculumOutlines';
import type { TeachableUnitDetailResponseCoreContent } from './teachableUnitDetailResponseCoreContent';
import type { TeachableUnitDetailResponseStemPractices } from './teachableUnitDetailResponseStemPractices';
import type { TeachableUnitDetailResponseTeacherNotes } from './teachableUnitDetailResponseTeacherNotes';
import type { TeachableUnitDetailResponseLearningProgressions } from './teachableUnitDetailResponseLearningProgressions';
import type { TeachableUnitDetailResponseLearningSuccessCriteria } from './teachableUnitDetailResponseLearningSuccessCriteria';
import type { TeachableUnitDetailResponseResources } from './teachableUnitDetailResponseResources';
import type { WeeklyTopicAbridgedResponse } from './weeklyTopicAbridgedResponse';

export interface TeachableUnitDetailResponse {
  createdAt: string;
  updatedAt: string;
  id: string;
  number: number;
  title: string;
  learningIntention: TeachableUnitDetailResponseLearningIntention;
  stemCurriculumOutlines: TeachableUnitDetailResponseStemCurriculumOutlines;
  coreContent: TeachableUnitDetailResponseCoreContent;
  stemPractices: TeachableUnitDetailResponseStemPractices;
  teacherNotes: TeachableUnitDetailResponseTeacherNotes;
  learningProgressions: TeachableUnitDetailResponseLearningProgressions;
  learningSuccessCriteria: TeachableUnitDetailResponseLearningSuccessCriteria;
  resources: TeachableUnitDetailResponseResources;
  weeklyTopics: WeeklyTopicAbridgedResponse[];
  bannerUrl: string;
}
