/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * harvest-api
 *  HarvestOS is a custom learning management platform for SERC

    It purposefully blends the learning management system with the
    game based learning platform to create a unique learning.

    
 * OpenAPI spec version: 0.3.5
 */

/**
 *  A model that represents a JWT token

    Used to send a newly created token or a refresh token with
    the type. For most use cases we send a bearer token.
    
 */
export interface Token {
  access_token: string;
  token_type: string;
}
