/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * harvest-api
 *  HarvestOS is a custom learning management platform for SERC

    It purposefully blends the learning management system with the
    game based learning platform to create a unique learning.

    
 * OpenAPI spec version: 0.3.5
 */
import type { UserResponseFirstName } from './userResponseFirstName';
import type { UserResponseLastInitial } from './userResponseLastInitial';
import type { UserResponseDisplayableName } from './userResponseDisplayableName';
import type { UserResponseAvatarUrl } from './userResponseAvatarUrl';

/**
 *  User profile 
    
 */
export interface UserResponse {
  createdAt: string;
  updatedAt: string;
  id: string;
  firstName: UserResponseFirstName;
  lastInitial: UserResponseLastInitial;
  displayableName: UserResponseDisplayableName;
  avatarUrl: UserResponseAvatarUrl;
}
